### PR TITLE
Validate Keystore Passwords Via Async Validator Before Proceeding With Onboarding

### LINKED ISSUE #136: Web UI validator import returns 500 internal server error if keystore-m password is wrong
Reported by @yorickdowne

# 🐞 Bug Report

### Description

Prysm 1.1.0 with Web UI and using the UI to create a wallet and import a keystore-m, on Ubuntu 20.04

If the password for the keystore-m is incorrect, Prysm Web UI will display an error 500 internal server error, but not inform the
user that the password for the keystore-m was incorrect. The wallet is created, just without keys.

Expected behavior: Prysm Web UI prompts user that the password for keystore-m is wrong, the way CLI import does.

### PR DESCRIPTION
**Pull request by rauljordan**
Resolves #136. Currently, our onboarding process takes users through a series of steps in which they have to upload keystore files, the password to those files, and their wallet password. If any step along the way is wrong, especially typing in an incorrect keystore password, the validator client gets stuck and the user never receives any feedback. Moreover, the validator still creates an empty wallet despite this flaw, which is not the intended behavior.

Instead, we send an API request to validate the keystore password during step (2) of the onboarding process, and show a form error in html if the password is incorrect before allowing the user to proceed.

### CODE REVIEW

File: src/app/modules/onboarding/validators/keystore.validator.ts [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+
+  correctPassword(): AsyncValidatorFn {
+    return (
+      control: AbstractControl
+    ): Promise<ValidationErrors | null> | Observable<ValidationErrors | null> => {
+      return control.valueChanges.pipe(
+        debounceTime(500),
+        take(1),
+        switchMap(_ => {
+          console.log('in switch map');
```
Comment (rkapka) [inline src/app/modules/onboarding/validators/keystore.validator.ts:39]: Please remove

File: src/app/modules/onboarding/validators/keystore.validator.ts [hunk 2]
```diff
@@ -0,0 +1,74 @@
...
+            console.log('no keystores password');
+            return of(null);
+          }
+          const req: ValidateKeystoresRequest = {
+            keystores,
+            keystoresPassword,
+          };
+          return this.walletService.validateKeystores(req).pipe(
+            map(() => {
+              console.log('in map null');
```
Comment (rkapka) [inline src/app/modules/onboarding/validators/keystore.validator.ts:56]: Please remove

File: src/app/modules/onboarding/validators/keystore.validator.ts [hunk 3]
```diff
@@ -0,0 +1,74 @@
...
+      control: AbstractControl
+    ): Promise<ValidationErrors | null> | Observable<ValidationErrors | null> => {
+      return control.valueChanges.pipe(
+        debounceTime(500),
+        take(1),
+        switchMap(_ => {
+          console.log('in switch map');
+          const keystores: string[] = control.get('keystoresImported')?.value;
+          if (!keystores.length) {
+            console.log('no keystores');
```
Comment (rkapka) [inline src/app/modules/onboarding/validators/keystore.validator.ts:42]: Do we want this log?

File: src/app/modules/onboarding/validators/keystore.validator.ts [hunk 4]
```diff
@@ -0,0 +1,74 @@
...
+            return of(null);
+          }
+          const keystoresPassword: string = control.get('keystoresPassword')?.value;
+          if (keystoresPassword === null || keystoresPassword === '') {
+            console.log('no keystores password');
```
Comment (rkapka) [inline src/app/modules/onboarding/validators/keystore.validator.ts:47]: Do we want this log?

File: src/app/modules/onboarding/validators/keystore.validator.ts [hunk 5]
```diff
@@ -0,0 +1,74 @@
...
+        take(1),
+        switchMap(_ => {
+          console.log('in switch map');
+          const keystores: string[] = control.get('keystoresImported')?.value;
+          if (!keystores.length) {
+            console.log('no keystores');
+            return of(null);
+          }
+          const keystoresPassword: string = control.get('keystoresPassword')?.value;
+          if (keystoresPassword === null || keystoresPassword === '') {
```
Comment (rkapka) [inline src/app/modules/onboarding/validators/keystore.validator.ts:46]: You should compare the trimmed value with `''`, otherwise `'   '` will pass the check.

File: src/app/modules/onboarding/validators/keystore.validator.ts [hunk 6]
```diff
@@ -0,0 +1,74 @@
...
+            console.log('no keystores password');
+            return of(null);
+          }
+          const req: ValidateKeystoresRequest = {
+            keystores,
+            keystoresPassword,
+          };
+          return this.walletService.validateKeystores(req).pipe(
+            map(() => {
```
Comment (rkapka) [inline src/app/modules/onboarding/validators/keystore.validator.ts:55]: Why does this map have only `return null`?

File: src/app/modules/onboarding/validators/keystore.validator.ts [hunk 7]
```diff
@@ -0,0 +1,74 @@
...
+              console.log('in map null');
+              return null;
+            }),
+            catchError((err: HttpErrorResponse) => {
+              let formErr: object;
+              if (err?.status === 400) {
+                formErr = { incorrectPassword: err.error?.message };
```
Comment (rkapka) [inline src/app/modules/onboarding/validators/keystore.validator.ts:62]: Since you write `error?`, shouldn't you handle a case where it's actually null and display a generic error message? Otherwise the user won't see anything, right? Or at least not anything meaningful.

File: src/app/modules/shared/components/import-accounts-form/import-accounts-form.component.ts [hunk 8]
```diff
@@ -1,9 +1,9 @@
-import { Component, Input } from '@angular/core';
+import {Component, Input } from '@angular/core';
 import { NgxFileDropEntry, FileSystemFileEntry } from 'ngx-file-drop';
 import { FormGroup } from '@angular/forms';
-import { from, throwError } from 'rxjs';
+import {from, throwError} from 'rxjs';
 import * as JSZip from 'jszip';
-import { catchError, take, tap } from 'rxjs/operators';
+import {catchError, take, takeUntil, tap} from 'rxjs/operators';
```
Comment (rkapka) [inline src/app/modules/shared/components/import-accounts-form/import-accounts-form.component.ts:6]: Are these new imports used anywhere?

File: src/app/proto/validator/accounts/v2/web_api.ts [hunk 9]
```diff
@@ -209,9 +191,13 @@ export interface ImportKeystoresResponse {
...
+export interface ValidateKeystoresRequest {
   /**
-   *  Number of accounts to create.
+   *  JSON encoded keystore list.
    */
-  numAccounts: number;
+  keystores: string[];
+  /**
+   *  Password to unlock the keystores.
+   */
```
Comment (rkapka) [inline src/app/proto/validator/accounts/v2/web_api.ts:201]: Is this a standard comment format? Seems a bit bulky.

**Review by rkapka — CHANGES_REQUESTED** [review]
Overall looks good, just a few minor complaints from me.

File: src/app/modules/onboarding/validators/keystore.validator.ts (hunk 6 above)
Comment (rauljordan) [reply src/app/modules/onboarding/validators/keystore.validator.ts:55]: It is a form validator. The positive case (meaning there is no error) should be returning null

File: src/app/modules/onboarding/validators/keystore.validator.ts (hunk 7 above)
Comment (rauljordan) [reply src/app/modules/onboarding/validators/keystore.validator.ts:62]: ah that's right, it will never be null here

File: src/app/proto/validator/accounts/v2/web_api.ts (hunk 9 above)
Comment (rauljordan) [reply src/app/proto/validator/accounts/v2/web_api.ts:201]: Yep standard, it is generated by proto-gen-ts

File: src/app/modules/shared/components/import-accounts-form/import-accounts-form.component.ts (hunk 8 above)
Comment (rauljordan) [reply src/app/modules/shared/components/import-accounts-form/import-accounts-form.component.ts]: Only tap is

**Comment by rauljordan** [comment]
Ready again @rkapka

File: src/app/modules/onboarding/validators/keystore.validator.ts (hunk 5 above)
Comment (rauljordan) [reply src/app/modules/onboarding/validators/keystore.validator.ts]: if I use .trim() I get a weird panic for some reason. But given that if control.get?.value if it is null, it will return ''. We shouldn't worry too much because the backend will handle these cases as well and couldn't figure out how to get around these issues fast enough

**Review by rkapka — APPROVED** [review]
